### PR TITLE
Feature/map

### PR DESCRIPTION
**Pull request by asbjornh**
Adds map component with support for markers and custom popups

### CODE REVIEW

**Comment by pellebjerkestrand** [comment]
What do you think about naming this `GoogleMap`?

**Comment by asbjornh** [comment]
> What do you think about naming this `GoogleMap`?

I don't really see the point but I don't have any strong feelings about it either. Should I?

**Comment by pellebjerkestrand** [comment]
> > What do you think about naming this `GoogleMap`?
> 
> I don't really see the point but I don't have any strong feelings about it either. Should I?

`Map` is so generic and one would have to investigate to know that there is only one provider (Google). And I was expecting Leaflet 😂.

**Comment by asbjornh** [comment]
@pellebjerkestrand done

**Comment by asbjornh** [comment]
@pellebjerkestrand bump

**Pull request merged**
